In [2]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path("../data/raw/bss_export_45.csv")

df = pd.read_csv(
    DATA_PATH,
    sep=";",
    encoding="utf-8",
    dtype=str,
    low_memory=False,
)

In [3]:
df.shape

(21700, 71)

In [4]:
df.head()

,ID_BSS,indice,designation,nom_abrege,libelle,lien_infoterre,google_maps,coupe_geologique,coupe_autre,log_geol_verifie,...,lex_gisement,lex_documents,reference,date_dossier,date_saisie,date_dern_maj,procede_geothermique,categorie_geothermie,usage_geothermie,relation_aquifere
0,BSS000WBCH,02926X0025,P,P,NaN,"=LIEN_HYPERTEXTE(""http://ficheinfoterre.brgm.f...","=LIEN_HYPERTEXTE(""http://maps.google.fr/?q=048...",Absente,Absente,Absent,...,NaN,"PIEZO-OCCASIONNELLE,PLAN-SITUATION.",NaN,20/05/1998,11/08/1999,26/08/2008,NaN,NaN,NaN,NaN
1,BSS000WBCJ,02926X0026,P,P,NaN,"=LIEN_HYPERTEXTE(""http://ficheinfoterre.brgm.f...","=LIEN_HYPERTEXTE(""http://maps.google.fr/?q=048...",Absente,Absente,Present,...,NaN,"PIEZO-OCCASIONNELLE,PLAN-SITUATION.",NaN,21/10/1998,11/08/1999,26/08/2008,NaN,NaN,NaN,NaN
2,BSS000WBDS,02926X0058,F,F,NaN,"=LIEN_HYPERTEXTE(""http://ficheinfoterre.brgm.f...","=LIEN_HYPERTEXTE(""http://maps.google.fr/?q=048...",Absente,Absente,Absent,...,NaN,"AUTORISATION,PLAN-SITUATION,PRODUCTION.",NaN,01/04/1998,24/02/1999,01/04/1998,NaN,NaN,NaN,NaN
3,BSS000WBFM,02927X1001,F,F,NaN,"=LIEN_HYPERTEXTE(""http://ficheinfoterre.brgm.f...","=LIEN_HYPERTEXTE(""http://maps.google.fr/?q=048...",Absente,Absente,Present,...,NaN,"ANALYSE-PHYSIQUE-EAU,BACTERIOLOGIE,CHIMIE-EAU,...",NaN,14/10/1993,14/10/1993,26/05/2015,NaN,NaN,NaN,NaN
4,BSS000WBFN,02927X1002,F,F,NaN,"=LIEN_HYPERTEXTE(""http://ficheinfoterre.brgm.f...","=LIEN_HYPERTEXTE(""http://maps.google.fr/?q=048...",Presente,Absente,Present,...,NaN,"BACTERIOLOGIE,CHIMIE-EAU,COUPE-GEOLOGIQUE,COUP...",NaN,14/10/1993,14/10/1993,26/05/2015,NaN,NaN,NaN,NaN

In [5]:
df.columns.tolist()

['ID_BSS',
 'indice',
 'designation',
 'nom_abrege',
 'libelle',
 'lien_infoterre',
 'google_maps',
 'coupe_geologique',
 'coupe_autre',
 'log_geol_verifie',
 'nb_scans',
 'nb_scans_coupe',
 'lex_organisme',
 'lex_type_declaration',
 'point_eau',
 'lex_sgr',
 'lex_num_departement',
 'lex_nom_departement',
 'lex_num_commune',
 'lex_insee_commune',
 'lex_nom_commune',
 'lieu_dit',
 'x_saisie',
 'y_saisie',
 'lex_projection_saisie',
 'lex_unite_saisie',
 'x_ref06',
 'y_ref06',
 'lex_projection_ref06',
 'lex_precision_xy',
 'lex_qual_position',
 'z_sol',
 'lex_prec_z_sol',
 'lex_mode_obtention_z',
 'z_bdalti',
 'lex_nature',
 'prof_investigation',
 'prof_accessible',
 'diametre_tubage',
 'prof_eau_sol',
 'lex_type_prof_eau_sol',
 'date_eau_sol',
 'z_origine_coupe',
 'lex_prec_z_origine_coupe',
 'date_coupe',
 'date_fin_travaux',
 'nombre_observations',
 'lex_num_carte_geol',
 'lex_nom_carte_geol',
 'coupure_huitieme',
 'lex_etat_physique',
 'lex_etat',
 'lex_execution',
 'lex_utilisation',
 'lex_recherche',
 'lex_exploitation',
 'lex_reconnaissance',
 'lex_fonction',
 'deb_fonction',
 'lex_usage',
 'deb_usage',
 'lex_gisement',
 'lex_documents',
 'reference',
 'date_dossier',
 'date_saisie',
 'date_dern_maj',
 'procede_geothermique',
 'categorie_geothermie',
 'usage_geothermie',
 'relation_aquifere']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21700 entries, 0 to 21699
Data columns (total 71 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID_BSS                    21700 non-null  object
 1   indice                    21700 non-null  object
 2   designation               21700 non-null  object
 3   nom_abrege                21696 non-null  object
 4   libelle                   1141 non-null   object
 5   lien_infoterre            21700 non-null  object
 6   google_maps               21700 non-null  object
 7   coupe_geologique          21700 non-null  object
 8   coupe_autre               21700 non-null  object
 9   log_geol_verifie          21700 non-null  object
 10  nb_scans                  21700 non-null  object
 11  nb_scans_coupe            21700 non-null  object
 12  lex_organisme             21160 non-null  object
 13  lex_type_declaration      21700 non-null  object
 14  point_eau                 21700 non-null  object
 15  lex_sgr                   21700 non-null  object
 16  lex_num_departement       21700 non-null  object
 17  lex_nom_departement       21700 non-null  object
 18  lex_num_commune           21700 non-null  object
 19  lex_insee_commune         21700 non-null  object
 20  lex_nom_commune           21700 non-null  object
 21  lieu_dit                  19144 non-null  object
 22  x_saisie                  21700 non-null  object
 23  y_saisie                  21700 non-null  object
 24  lex_projection_saisie     21700 non-null  object
 25  lex_unite_saisie          21700 non-null  object
 26  x_ref06                   21700 non-null  object
 27  y_ref06                   21700 non-null  object
 28  lex_projection_ref06      21700 non-null  object
 29  lex_precision_xy          14813 non-null  object
 30  lex_qual_position         9316 non-null   object
 31  z_sol                     21604 non-null  object
 32  lex_prec_z_sol            19776 non-null  object
 33  lex_mode_obtention_z      166 non-null    object
 34  z_bdalti                  17589 non-null  object
 35  lex_nature                21615 non-null  object
 36  prof_investigation        19480 non-null  object
 37  prof_accessible           42 non-null     object
 38  diametre_tubage           7168 non-null   object
 39  prof_eau_sol              7608 non-null   object
 40  lex_type_prof_eau_sol     1501 non-null   object
 41  date_eau_sol              7256 non-null   object
 42  z_origine_coupe           6150 non-null   object
 43  lex_prec_z_origine_coupe  6503 non-null   object
 44  date_coupe                5677 non-null   object
 45  date_fin_travaux          19115 non-null  object
 46  nombre_observations       15208 non-null  object
 47  lex_num_carte_geol        21700 non-null  object
 48  lex_nom_carte_geol        21700 non-null  object
 49  coupure_huitieme          21700 non-null  object
 50  lex_etat_physique         425 non-null    object
 51  lex_etat                  17278 non-null  object
 52  lex_execution             14886 non-null  object
 53  lex_utilisation           11516 non-null  object
 54  lex_recherche             4101 non-null   object
 55  lex_exploitation          14739 non-null  object
 56  lex_reconnaissance        2294 non-null   object
 57  lex_fonction              1677 non-null   object
 58  deb_fonction              1677 non-null   object
 59  lex_usage                 1030 non-null   object
 60  deb_usage                 1030 non-null   object
 61  lex_gisement              18 non-null     object
 62  lex_documents             19511 non-null  object
 63  reference                 6975 non-null   object
 64  date_dossier              17617 non-null  object
 65  date_saisie               21700 non-null  object
 66  date_dern_maj             21516 non-null  object
 67  procede_geothermique      793 non-null    object
 68  categorie_geothermie      790 non-null    object
 69  usage_geothermie          185 non-null    object
 70  relation_aquifere         108 non-null    object
dtypes: object(71)
memory usage: 11.8+ MB

In [7]:
df["ID_BSS"].nunique(), len(df)

(21700, 21700)

In [8]:
df["ID_BSS"].isna().sum()

np.int64(0)

In [9]:
df["ID_BSS"].duplicated().sum()

np.int64(0)

In [10]:
profile = pd.DataFrame({
    "column": df.columns,
    "non_null": [df[c].notna().sum() for c in df.columns],
    "missing_pct": [df[c].isna().mean() * 100 for c in df.columns],
    "unique": [df[c].nunique(dropna=True) for c in df.columns],
})

profile.sort_values("missing_pct")

                  column  non_null  missing_pct  unique
0                 ID_BSS     21700     0.000000   21700
1                 indice     21700     0.000000   21700
2            designation     21700     0.000000    2790
5         lien_infoterre     21700     0.000000   21700
7       coupe_geologique     21700     0.000000       2
..                   ...       ...          ...     ...
69      usage_geothermie       185    99.147465       3
33  lex_mode_obtention_z       166    99.235023       5
70     relation_aquifere       108    99.502304       3
37       prof_accessible        42    99.806452      33
61          lex_gisement        18    99.917051       6

[71 rows x 4 columns]

In [11]:
profile["missing_pct"] = profile["missing_pct"].round(2)

profile.sort_values(
    "missing_pct"
).reset_index(drop=True)

                  column  non_null  missing_pct  unique
0                 ID_BSS     21700         0.00   21700
1                 indice     21700         0.00   21700
2            designation     21700         0.00    2790
3         lien_infoterre     21700         0.00   21700
4       coupe_geologique     21700         0.00       2
..                   ...       ...          ...     ...
66      usage_geothermie       185        99.15       3
67  lex_mode_obtention_z       166        99.24       5
68     relation_aquifere       108        99.50       3
69       prof_accessible        42        99.81      33
70          lex_gisement        18        99.92       6

[71 rows x 4 columns]

In [12]:
profile.sort_values(
    ["unique", "missing_pct"]
).reset_index(drop=True)

                  column  non_null  missing_pct  unique
0                lex_sgr     21700          0.0       1
1    lex_num_departement     21700          0.0       1
2    lex_nom_departement     21700          0.0       1
3   lex_projection_ref06     21700          0.0       1
4       coupe_geologique     21700          0.0       2
..                   ...       ...          ...     ...
66               x_ref06     21700          0.0   19190
67           google_maps     21700          0.0   21622
68                ID_BSS     21700          0.0   21700
69                indice     21700          0.0   21700
70        lien_infoterre     21700          0.0   21700

[71 rows x 4 columns]

In [13]:
print(profile.sort_values("missing_pct").to_string(index=False))

                  column  non_null  missing_pct  unique
                  ID_BSS     21700         0.00   21700
                  indice     21700         0.00   21700
             designation     21700         0.00    2790
          lien_infoterre     21700         0.00   21700
        coupe_geologique     21700         0.00       2
             google_maps     21700         0.00   21622
        log_geol_verifie     21700         0.00       2
             coupe_autre     21700         0.00       2
    lex_type_declaration     21700         0.00       3
               point_eau     21700         0.00       2
                nb_scans     21700         0.00      78
          nb_scans_coupe     21700         0.00      31
                 lex_sgr     21700         0.00       1
         lex_num_commune     21700         0.00     348
     lex_nom_departement     21700         0.00       1
     lex_num_departement     21700         0.00       1
    lex_projection_ref06     21700         0.00       1
        lex_unite_saisie     21700         0.00       4
                 x_ref06     21700         0.00   19190
       lex_insee_commune     21700         0.00     348
         lex_nom_commune     21700         0.00     348
                x_saisie     21700         0.00   14009
                y_saisie     21700         0.00   12053
   lex_projection_saisie     21700         0.00       6
                 y_ref06     21700         0.00   17587
        coupure_huitieme     21700         0.00       8
      lex_nom_carte_geol     21700         0.00      23
      lex_num_carte_geol     21700         0.00      23
             date_saisie     21700         0.00    2468
              nom_abrege     21696         0.02    3011
              lex_nature     21615         0.39      19
                   z_sol     21604         0.44    2263
           date_dern_maj     21516         0.85    1607
           lex_organisme     21160         2.49      10
          lex_prec_z_sol     19776         8.87      12
           lex_documents     19511        10.09    1832
      prof_investigation     19480        10.23    1935
                lieu_dit     19144        11.78   14309
        date_fin_travaux     19115        11.91    6357
            date_dossier     17617        18.82    2946
                z_bdalti     17589        18.94     166
                lex_etat     17278        20.38     973
     nombre_observations     15208        29.92      36
           lex_execution     14886        31.40     266
        lex_precision_xy     14813        31.74      11
        lex_exploitation     14739        32.08      60
         lex_utilisation     11516        46.93     242
       lex_qual_position      9316        57.07       2
            prof_eau_sol      7608        64.94    1569
            date_eau_sol      7256        66.56    3270
         diametre_tubage      7168        66.97     275
               reference      6975        67.86    5119
lex_prec_z_origine_coupe      6503        70.03       9
         z_origine_coupe      6150        71.66     764
              date_coupe      5677        73.84    3153
           lex_recherche      4101        81.10      19
      lex_reconnaissance      2294        89.43     165
            lex_fonction      1677        92.27      32
            deb_fonction      1677        92.27     601
   lex_type_prof_eau_sol      1501        93.08       4
                 libelle      1141        94.74     689
               deb_usage      1030        95.25     262
               lex_usage      1030        95.25      25
    procede_geothermique       793        96.35       2
    categorie_geothermie       790        96.36       3
       lex_etat_physique       425        98.04       4
        usage_geothermie       185        99.15       3
    lex_mode_obtention_z       166        99.24       5
       relation_aquifere       108        99.50       3
         prof_accessible        42        99.81      33
            lex_gisement        18        99.92       6

In [14]:
lex_columns = [c for c in df.columns if c.startswith("lex_")]

len(lex_columns), lex_columns

(31,
 ['lex_organisme',
  'lex_type_declaration',
  'lex_sgr',
  'lex_num_departement',
  'lex_nom_departement',
  'lex_num_commune',
  'lex_insee_commune',
  'lex_nom_commune',
  'lex_projection_saisie',
  'lex_unite_saisie',
  'lex_projection_ref06',
  'lex_precision_xy',
  'lex_qual_position',
  'lex_prec_z_sol',
  'lex_mode_obtention_z',
  'lex_nature',
  'lex_type_prof_eau_sol',
  'lex_prec_z_origine_coupe',
  'lex_num_carte_geol',
  'lex_nom_carte_geol',
  'lex_etat_physique',
  'lex_etat',
  'lex_execution',
  'lex_utilisation',
  'lex_recherche',
  'lex_exploitation',
  'lex_reconnaissance',
  'lex_fonction',
  'lex_usage',
  'lex_gisement',
  'lex_documents'])

In [15]:
df["categorie_geothermie"].sample(25).tolist()

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [16]:
for col in lex_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- lex_organisme ---
lex_organisme
BRGM                         20205
NaN                            540
CEREMA                         239
Portail DUPLOS                 222
INRAP                          183
Portail GMI                    165
Portail forage domestique      109
GESFOR                          25
DREAL                            5
AGENCE DE L'EAU                  4
MINISTERE ENVIRONNEMENT          3
Name: count, dtype: int64

--- lex_type_declaration ---
lex_type_declaration
Code Minier         12270
Hors Declaration     8771
Police de l'eau       659
Name: count, dtype: int64

--- lex_sgr ---
lex_sgr
SGR/CEN    21700
Name: count, dtype: int64

--- lex_num_departement ---
lex_num_departement
45    21700
Name: count, dtype: int64

--- lex_nom_departement ---
lex_nom_departement
LOIRET    21700
Name: count, dtype: int64

--- lex_num_commune ---
lex_num_commune
234    746
232    594
274    570
300    377
286    319
272    280
298    257
284    255
004    253
097    237
317    217
173    217
146    209
338    190
082    187
Name: count, dtype: int64

--- lex_insee_commune ---
lex_insee_commune
45234    746
45232    594
45274    570
45300    377
45286    319
45272    280
45298    257
45284    255
45004    253
45097    237
45317    217
45173    217
45146    209
45338    190
45082    187
Name: count, dtype: int64

--- lex_nom_commune ---
lex_nom_commune
ORLEANS                     746
OLIVET                      594
SAINT DENIS EN VAL          570
SANDILLON                   377
SAINT JEAN LE BLANC         319
SAINT CYR EN VAL            280
SAINT PRYVE SAINT MESMIN    257
SAINT JEAN DE BRAYE         255
AMILLY                      253
CHUELLES                    237
TAVERS                      217
JARGEAU                     217
FERTE SAINT AUBIN           209
VILLEMANDEUR                190
CHATEAUNEUF SUR LOIRE       187
Name: count, dtype: int64

--- lex_projection_saisie ---
lex_projection_saisie
Lambert 2 - Centre             17454
Lambert 1 - Nord                1843
Lambert-93                      1080
Lambert 2 étendu                 848
Longitude/Latitude (WGS 84)      460
Lambert-93 zone 7 CC48            15
Name: count, dtype: int64

--- lex_unite_saisie ---
lex_unite_saisie
Kilomètre               19219
Mètre                    2021
Degré décimal             346
Degré minute seconde      114
Name: count, dtype: int64

--- lex_projection_ref06 ---
lex_projection_ref06
Lambert-93    21700
Name: count, dtype: int64

--- lex_precision_xy ---
lex_precision_xy
M025    12831
NaN      6887
C005     1055
M050      359
M010      323
M020      128
M001       92
M100       20
M200        2
M080        1
M250        1
M500        1
Name: count, dtype: int64

--- lex_qual_position ---
lex_qual_position
NaN        12384
BON         9294
MAUVAIS       22
Name: count, dtype: int64

--- lex_prec_z_sol ---
lex_prec_z_sol
EPD    14384
MNT     2858
NaN     1924
RNG     1430
M01      506
IGN      261
ENG      125
M50       74
C10       67
GPS       39
M05       20
C50        8
M10        4
Name: count, dtype: int64

--- lex_mode_obtention_z ---
lex_mode_obtention_z
NaN                                                      21534
Mode d’obtention inconnu                                   136
Relevé GPS/GNSS différentiel                                15
Déterminé par MNT                                           10
Carte topographique géoréférencée (type IGN ou autre)        4
Relevé GPS/GNSS autonome                                     1
Name: count, dtype: int64

--- lex_nature ---
lex_nature
FORAGE                          10875
PUITS                            7155
SONDAGE                          2280
EXCAVATION-CIEL-OUVERT            910
SOURCE                            180
CAVITE-NATURELLE                   87
NaN                                85
AFFLEUREMENT-EAU                   61
CAVITE-ANTHROPIQUE                 11
MESURE                             11
STATION-JAUGEAGE                   10
PRISE-EAU                           6
INDICATION                          6
AFFLEUREMENT-EAU-SOUTERRAINE        6
GITE-MINIER                         5
Name: count, dtype: int64

--- lex_type_prof_eau_sol ---
lex_type_prof_eau_sol
NaN                                                              20199
premier niveau d'eau rencontré                                     859
profondeur de l'eau observée en fin de travaux dans l'ouvrage      611
ouvrage sec                                                         21
niveau d'eau artésien                                               10
Name: count, dtype: int64

--- lex_prec_z_origine_coupe ---
lex_prec_z_origine_coupe
NaN    15197
M01     5022
EPD      992
C10      363
RNG       95
M05       11
IGN       11
ENG        7
C50        1
M10        1
Name: count, dtype: int64

--- lex_num_carte_geol ---
lex_num_carte_geol
0398    3637
0363    3574
0365    2222
0399    1895
0397    1240
0328    1213
0400    1164
0364    1152
0366    1038
0362     883
0327     861
0329     741
0432     707
0293     344
0330     303
Name: count, dtype: int64

--- lex_nom_carte_geol ---
lex_nom_carte_geol
LA FERTE-ST-AUBIN        3637
ORLEANS                  3574
MONTARGIS                2222
CHATEAUNEUF-SUR-LOIRE    1895
BEAUGENCY                1240
PITHIVIERS               1213
CHATILLON-COLIGNY        1164
BELLEGARDE-DU-LOIRET     1152
COURTENAY                1038
PATAY                     883
NEUVILLE-AUX-BOIS         861
CHATEAU-LANDON            741
GIEN                      707
MALESHERBES               344
CHEROY                    303
Name: count, dtype: int64

--- lex_etat_physique ---
lex_etat_physique
NaN             21275
Opérationnel      379
Rebouché           32
Non réalisé         9
Prévu               5
Name: count, dtype: int64

--- lex_etat ---
lex_etat
NaN                                               4422
REBOUCHE.                                         2189
EXPLOITE.                                         1844
MESURE,EXPLOITE.                                  1004
TUBE-PLASTIQUE,MESURE,EXPLOITE.                    882
MESURE.                                            853
MESURE,NON-EXPLOITE.                               609
EXPLOITE,MESURE.                                   607
NON-EXPLOITE,MESURE.                               475
ACCES,EXPLOITE,MESURE,POMPE,PRELEV,TUBE-METAL.     450
ACCES,MESURE,EXPLOITE.                             438
MESURE,EXPLOITE,TUBE-PLASTIQUE.                    362
NON-EXPLOITE.                                      354
TUBE-METAL,EXPLOITE.                               334
ABANDONNE.                                         321
Name: count, dtype: int64

--- lex_execution ---
lex_execution
NaN                  6814
MANUEL.              2962
FONCAGE-MANUEL.      1958
BATTAGE,TREPAN.      1559
MARTEAU-FOND,AIR.    1241
ROTATION,TREPAN.      931
MARTEAU-FOND.         850
BATTAGE.              850
TARIERE.              769
ROTATION.             628
TREPAN.               550
CAROTTAGE.            265
BOUE,ROTATION.        216
TREPAN,BATTAGE.       188
PUITS.                162
Name: count, dtype: int64

--- lex_utilisation ---
lex_utilisation
NaN                              10184
EAU-ASPERSION.                    3280
EAU-DOMESTIQUE.                   2023
EAU-IRRIGATION.                   1156
EAU-ASPERSION,EAU-DOMESTIQUE.      451
AEP.                               393
EAU-DOMESTIQUE,EAU-ASPERSION.      275
EAU-ASPERSION,EAU-AGRICOLE.        272
PIEZOMETRE.                        263
EAU-AGRICOLE.                      262
PIEZOMETRE,QUALITE-EAU.            252
EAU-INDIVIDUELLE.                  239
EAU-AGRICOLE,EAU-ASPERSION.        232
EAU-INDUSTRIELLE.                  197
POMPE-A-CHALEUR.                   195
Name: count, dtype: int64

--- lex_recherche ---
lex_recherche
NaN                    17599
EAU.                    2236
HYDROCARBURE.           1547
MATERIAUX.               136
EAU,GEOTHERMIE.           57
ARGILE.                   39
GEOTHERMIE-TBE.           28
GRAVIER,SABLE.            22
SABLE,GRAVIER.            11
ARGILE,MATERIAUX.          8
FER.                       4
MATERIAUX,CALCAIRE.        4
MARNE.                     2
HUILE,HYDROCARBURE.        1
GEOTHERMIE.                1
Name: count, dtype: int64

--- lex_exploitation ---
lex_exploitation
EAU.                            13181
NaN                              6961
CALCAIRE.                         231
GEOTHERMIE-TBE.                   182
HYDROCARBURE.                     164
SABLE.                            140
GEOTHERMIE-TBE,EAU.               117
EAU,GEOTHERMIE-TBE.               109
REJET-EAU-USEE.                    60
EAU,ENERGIE-GEOTHERMIQUE.          58
SABLE,GRAVIER,GRAVIER-SABLE.       51
GRAVIER-SABLE.                     48
MARNE.                             45
EAU,REJET-EAU-USEE.                44
ARGILE.                            43
Name: count, dtype: int64

--- lex_reconnaissance ---
lex_reconnaissance
NaN                                 19406
GEOLOGIE.                             310
POLLUTION-NAPPE.                      248
AUTOROUTE.                            232
SOL-FONDATION.                        168
GEOTHERMIE.                           150
AQUEDUC.                              111
DEBIT-RIVIERE.                         72
FLUCTUATION-NAPPE.                     70
GEOLOGIE,GEOTECHNIQUE,AUTOROUTE.       62
CARTE-GEOLOGIQUE.                      59
COLLECTEUR-EGOUT.                      58
CENTRALE-NUCLEAIRE.                    56
IMPLANTATION,AUTOROUTE.                44
BATIMENT-LOURD.                        36
Name: count, dtype: int64

--- lex_fonction ---
lex_fonction
NaN                                                                        20023
EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE                                   707
RECONNAISSANCE/GEOLOGIE/GEOTECHNIQUE                                         220
EXPLOITATION/EAU                                                             196
RECONNAISSANCE/ARCHEOLOGIE-PREVENTIVE                                        183
SURVEILLANCE/EAU/PIEZOMETRIE                                                 101
RECONNAISSANCE/ROCHES-SUBSTANCES                                              78
EXPLOITATION/ROCHES-SUBSTANCES                                                36
EXPLOITATION/EAU|EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE                   25
RECONNAISSANCE/EAU/PARAMETRES-HYDRODYNAMIQUES                                 24
RECONNAISSANCE/EAU                                                            13
EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE|STOCKAGE/EAU/INJECTION             13
EXPLOITATION/EAU/PRELEVEMENT|EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE       10
EXPLOITATION/EAU/INJECTION|EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE         10
SURVEILLANCE/EAU/QUALITOMETRIE                                                10
Name: count, dtype: int64

--- lex_usage ---
lex_usage
NaN                                                      20670
EAU/ENERGIE/GEOTHERMIE-SUR-AQUIFERE                        654
GEOTHERMIE-AVEC-SONDE                                      134
EAU/DOMESTIQUE                                             103
EAU/AEP                                                     30
EAU/AGRICULTURE/IRRIGATION                                  18
EAU/AGRICULTURE/IRRIGATION/ASPERSION                        18
EAU/LOISIRS/ARROSAGE-LOISIRS                                18
EAU/AEP/ALIMENTATION-COLLECTIVE                             14
PAS-D-USAGE                                                  6
EAU/AEP/ALIMENTATION-INDIVIDUELLE                            5
EAU/EMBOUTEILLAGE                                            4
EAU/AGRICULTURE/IRRIGATION/IRRIGATION-GOUTTE-A-GOUTTE        4
EAU/AEP|EAU/AEP                                              3
EAU/INDUSTRIE/INDUSTRIE-HORS-AGROALIMENTAIRE                 3
Name: count, dtype: int64

--- lex_gisement ---
lex_gisement
NaN                      21682
INCONNU.                     5
AMAS.                        5
AMAS,STRATIFORME.            4
INCONNU,COUCHE.              2
COUCHE.                      1
VOLCANO-SEDIMENTAIRE.        1
Name: count, dtype: int64

--- lex_documents ---
lex_documents
PIEZO-OCCASIONNELLE,PLAN-SITUATION.                                                                                       3669
NaN                                                                                                                       2189
PLAN-SITUATION.                                                                                                            893
COUPE-GEOLOGIQUE,DIAGRAPHIE,VITESSE-SONIQUE.                                                                               826
COUPE-GEOLOGIQUE.                                                                                                          747
COUPE-GEOLOGIQUE,COUPE-TECHNIQUE,DECLARATION-CODE-MINIER,PIEZO-OCCASIONNELLE,PLAN-SITUATION,PRODUCTIVITE.                  636
COUPE-TECHNIQUE,PLAN-POSITION.                                                                                             544
DECLARATION-CODE-MINIER,PLAN-SITUATION.                                                                                    452
COUPE-GEOLOGIQUE,PLAN-SITUATION.                                                                                           353
COUPE-FOREUR,COUPE-TECHNIQUE,DECLARATION-CODE-MINIER,PIEZO-OCCASIONNELLE,PLAN-SITUATION,PRODUCTION,PRODUCTIVITE.           300
AUTORISATION,COUPE-GEOLOGIQUE,COUPE-TECHNIQUE,DECLARATION-CODE-MINIER,PIEZO-OCCASIONNELLE,PLAN-SITUATION,PRODUCTIVITE.     245
COUPE-FOREUR,DECLARATION-CODE-MINIER.                                                                                      245
DIAGRAPHIE.                                                                                                                202
CHIMIE-EAU,PIEZO-OCCASIONNELLE,PLAN-SITUATION.                                                                             201
COUPE-GEOLOGIQUE,COUPE-TECHNIQUE,DECLARATION-CODE-MINIER,PIEZO-OCCASIONNELLE,PLAN-SITUATION,PRODUCTION.                    195
Name: count, dtype: int64

In [17]:
r = df["lex_recherche"].notna()
rec = df["lex_reconnaissance"].notna()

print("Recherche only:", (r & ~rec).sum())
print("Reconnaissance only:", (~r & rec).sum())
print("Both:", (r & rec).sum())
print("Neither:", (~r & ~rec).sum())

Recherche only: 3837
Reconnaissance only: 2030
Both: 264
Neither: 15569

In [18]:
df.loc[
    r & rec,
    ["ID_BSS", "lex_nature", "lex_recherche", "lex_reconnaissance"]
].head(20)

         ID_BSS lex_nature  lex_recherche          lex_reconnaissance
33   BSS000WBGX    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
34   BSS000WBGY    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
35   BSS000WBGZ    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
73   BSS000WBKV    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
74   BSS000WBKW    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
75   BSS000WBKX    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
163  BSS000WCCT    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
361  BSS000WCMZ      PUITS           EAU.                   DRAINAGE.
505  BSS000YCKP     FORAGE           EAU.  DRAINAGE,REJET-EAUX-USEES.
512  BSS000YCLT    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
592  BSS000YCQS    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
593  BSS000YCQT    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
690  BSS000YCUV     FORAGE  HYDROCARBURE.                   GEOLOGIE.
691  BSS000YCUW    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
692  BSS000YCUX    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
785  BSS000YDCJ    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
786  BSS000YDCK    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
787  BSS000YDCL    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
788  BSS000YDCM    SONDAGE  HYDROCARBURE.                   GEOLOGIE.
918  BSS000YDKV    SONDAGE  HYDROCARBURE.                   GEOLOGIE.

In [19]:
for col in [
    "deb_usage",
    "lex_gisement",
    "reference",
    "date_dossier",
    "procede_geothermique",
    "categorie_geothermie",
    "usage_geothermie",
    "relation_aquifere",
]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- deb_usage ---
deb_usage
NaN           20670
01/01/1900      641
14/06/2023       16
24/03/2021       15
12/02/2024       12
20/02/2023        6
13/06/2024        6
02/06/2023        5
01/01/2007        4
16/03/2018        4
31/03/2022        4
03/08/2023        4
22/02/2018        4
23/06/2023        3
01/01/1966        3
31/03/2023        3
26/07/2023        3
05/10/2006        3
30/06/2021        3
31/10/2005        3
Name: count, dtype: int64

--- lex_gisement ---
lex_gisement
NaN                      21682
INCONNU.                     5
AMAS.                        5
AMAS,STRATIFORME.            4
INCONNU,COUCHE.              2
COUCHE.                      1
VOLCANO-SEDIMENTAIRE.        1
Name: count, dtype: int64

--- reference ---
reference
NaN                                                                                                                                                                                             14725
CARTE GEOLOGIQUE 1/50000                                                                                                                                                                          143
1) BRGM DSGR 67 A 21                                                                                                                                                                              133
CF 03976X0146                                                                                                                                                                                     125
TRANCHE 1 19-0506                                                                                                                                                                                 104
TRAMWAY                                                                                                                                                                                            65
CAMPAGNE DE 60 SONDAGES : CF. DOSSIER 0365/5X/0013                                                                                                                                                 57
CF. DOSSIER 0400/5X/0080                                                                                                                                                                           53
PUITS SIGNALE SUR CADASTRE                                                                                                                                                                         46
TRANCHE 1 , LOT2                                                                                                                                                                                   45
TRANCHE 1                                                                                                                                                                                          34
PLAN DE SITUATION SUR 0274 , DOSSIERS 0274 & 0356 À 0392                                                                                                                                           30
GISEMENT : CALC. DE PITHIVIERS                                                                                                                                                                     30
FORAGE MITOYEN                                                                                                                                                                                     29
FORAGE DE POMPAGE POUR P.A.C.                                                                                                                                                                      24
RESEAU PIEZOMETRIQUE DE LA NAPPE DE BEAUCE  (DIREN/SEMA REGION CENTRE)                                                                                                                             23
FORAGE DE POMPAGE POUR PAC                                                                                                                                                                         21
RAPPORT 75 SGN 324 BDP- FEV 96- RAPP. 78 SGN 552 BDP- DOUBLEMENT DE LA RN 152 ENTRE ORLEANS ET CHATEAUNEUF S/LOIRE (LT) -AVANT PROJET DETAILLE -ETUDE GEOTECHNIQUE CAILLOL-DESPREZ- OCT 1978       20
RAPPORT 75 SGN 324 BDP-  FEV 1976                                                                                                                                                                  20
CAMPAGNE DE 20 SONDAGES : DOSSIERS 0399/1X/0376 À 0394 ET 0399/1X/0273                                                                                                                             20
Name: count, dtype: int64

--- date_dossier ---
date_dossier
NaN           4083
20/05/1998     224
01/07/2026     183
20/07/1998     181
09/12/2021     149
08/02/2002     136
30/11/1998     122
06/11/2002     120
10/05/2004     112
30/09/1998     108
12/01/1998     108
15/05/1998     107
31/10/1998      95
14/01/2002      94
01/01/1986      93
07/12/2021      90
25/10/2004      85
14/11/2000      83
04/03/2002      78
26/10/1998      74
Name: count, dtype: int64

--- procede_geothermique ---
procede_geothermique
NaN         20907
aquifère      656
sonde         137
Name: count, dtype: int64

--- categorie_geothermie ---
categorie_geothermie
NaN                                                        20910
Géothermie de surface avant textes de loi GMI (<100 m)       617
Géothermie de minime importance (GMI)                        169
Géothermie basse température (jusqu'à 150°C) avant 2020        4
Name: count, dtype: int64

--- usage_geothermie ---
usage_geothermie
NaN                                                                                                21515
Chauffage et autres productions de chaleur à usage industriel                                        122
Chauffage et autres productions de chaleur à usage industriel|Rafraichissement                        49
Production d'eau chaude sanitaire|Chauffage et autres productions de chaleur à usage industriel       14
Name: count, dtype: int64

--- relation_aquifere ---
relation_aquifere
NaN                                                       21592
Point de prélèvement pour la production de chaleur           57
Point de réinjection pour la production de chaleur           50
Point mixte  prélèvement/réinjection suivant la saison        1
Name: count, dtype: int64

In [21]:
df["lex_fonction"].sample(25)

7793                                                   NaN
3798                                                   NaN
9061                                                   NaN
3401                                                   NaN
21502    EXPLOITATION/EAU/INJECTION|EXPLOITATION/GEOTHE...
21445                                     EXPLOITATION/EAU
16107                                                  NaN
3045                                                   NaN
19992           EXPLOITATION/GEOTHERMIE/TRES-BASSE-ENERGIE
4386                                                   NaN
21543                RECONNAISSANCE/ARCHEOLOGIE-PREVENTIVE
2619                                                   NaN
15102                                                  NaN
17705                                                  NaN
13954                                                  NaN
20911                                     EXPLOITATION/EAU
11295                       EXPLOITATION/ROCHES-SUBSTANCES
8793                                                   NaN
17082                                                  NaN
13537                                                  NaN
10559                                                  NaN
19948                                                  NaN
20322                                                  NaN
1984                                                   NaN
16231                                                  NaN
Name: lex_fonction, dtype: object